apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: order-app-chart
    repoURL: https://github.com/ramanujds/gitops-repo-forvia
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../environments/dev/values/order-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true